name: Dockstore

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install Dockstore dependencies
      run: |
        mkdir -p ~/bin
        curl -L -o ~/bin/dockstore https://github.com/dockstore/dockstore/releases/download/1.9.0/dockstore
        chmod +x ~/bin/dockstore
        mkdir -p ~/.dockstore
        printf "token: ${{secrets.DOCKSTORE_TOKEN}}\nserver-url: https://dockstore.org/api\n" > ~/.dockstore/config

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        export PATH=~/bin:$PATH
        python dockstore.py tests/test-descriptions.yaml \
        ${GITHUB_REF#refs/*/} \
        sagebionetworks/synapsepythonclient \
        git@github.com:Sage-Bionetworks-Workflows/dockstore-tool-synapseclient.git
